### BEGIN SET TIME ZONE
ln -snf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime && echo Asia/Jakarta > /etc/timezone
### END SET TIME ZONE

yum install -y epel-release \
&& yum update -y \
&& yum install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm \
&& yum install -y nano htop postgresql12-server postgresql12-contrib \
&& yum -y clean all \
&& rm -rf /var/cache/yum

RUN systemctl enable postgresql-12.service

/usr/pgsql-12/bin/postgresql-12-setup initdb

sed -i '/^listen_addresses/s/^/#/g' /var/lib/pgsql/12/data/postgresql.conf \
&& sed -i '/^port/s/^/#/g' /var/lib/pgsql/12/data/postgresql.conf \
&& sed -i '/^shared_preload_libraries/s/^/#/g' /var/lib/pgsql/12/data/postgresql.conf \
&& sed -i '/^max_connections/s/^/#/g' /var/lib/pgsql/12/data/postgresql.conf \
&& sed -i '/^shared_buffers/s/^/#/g' /var/lib/pgsql/12/data/postgresql.conf \
&& sed -i '/^effective_cache_size/s/^/#/g' /var/lib/pgsql/12/data/postgresql.conf \
&& sed -i '/^work_mem/s/^/#/g' /var/lib/pgsql/12/data/postgresql.conf \
&& sed -i '/^maintenance_work_mem/s/^/#/g' /var/lib/pgsql/12/data/postgresql.conf \
&& sed -i '/^min_wal_size/s/^/#/g' /var/lib/pgsql/12/data/postgresql.conf \
&& sed -i '/^max_wal_size/s/^/#/g' /var/lib/pgsql/12/data/postgresql.conf \
&& sed -i '/^checkpoint_completion_target/s/^/#/g' /var/lib/pgsql/12/data/postgresql.conf \
&& sed -i '/^wal_buffers/s/^/#/g' /var/lib/pgsql/12/data/postgresql.conf \
&& sed -i '/^random_page_cost/s/^/#/g' /var/lib/pgsql/12/data/postgresql.conf \
&& sed -i '/^effective_io_concurrency/s/^/#/g' /var/lib/pgsql/12/data/postgresql.conf \
&& sed -i '/^max_worker_processes/s/^/#/g' /var/lib/pgsql/12/data/postgresql.conf \
&& sed -i '/^max_parallel_workers_per_gather/s/^/#/g' /var/lib/pgsql/12/data/postgresql.conf \
&& sed -i '/^max_parallel_workers/s/^/#/g' /var/lib/pgsql/12/data/postgresql.conf \
&& sed -i '/^track_activity_query_size/s/^/#/g' /var/lib/pgsql/12/data/postgresql.conf \
&& sed -i '/^pg_stat_statements.track/s/^/#/g' /var/lib/pgsql/12/data/postgresql.conf \
&& sed -i '/^log_filename/s/^/#/g' /var/lib/pgsql/12/data/postgresql.conf \
&& sed -i '/^huge_pages/s/^/#/g' /var/lib/pgsql/12/data/postgresql.conf

echo $'
## 2 Core, 2GB Memory
# Memory Configuration
shared_buffers = 1GB
effective_cache_size = 3GB
work_mem = 10MB
maintenance_work_mem = 205MB

# Checkpoint Related Configuration
min_wal_size = 2GB
max_wal_size = 3GB
checkpoint_completion_target = 0.9
wal_buffers = -1

# Network Related Configuration
listen_addresses = \'*\'
port = 5432
max_connections = 100

# Storage Configuration
random_page_cost = 1.1
effective_io_concurrency = 200

# Worker Processes
max_worker_processes = 8
max_parallel_workers_per_gather = 2
max_parallel_workers = 2

shared_preload_libraries = \'pg_stat_statements\'

# Increase the max size of the query strings Postgres records
track_activity_query_size = 2048

# Track statements generated by stored procedures as well
pg_stat_statements.track = all
log_filename = \'postgresql-%Y%m%d.log\'
huge_pages = try\n' >> /var/lib/pgsql/12/data/postgresql.conf

echo $'# Accept all host
host	all	all	0.0.0.0/0	md5

# Replication
host	replication	replication	10.0.0.101/24	md5
host	replication	replication	10.0.0.102/24	md5
host	replication	replication	10.0.0.103/24	md5
host	replication	replication	10.0.0.104/24	md5
host	replication	replication	10.0.0.105/24	md5' >> /var/lib/pgsql/12/data/pg_hba.conf

chown postgres:postgres /usr/pgsql-12/bin/*
chown -Rf postgres:postgres /var/lib/pgsql/

#PGPASSWORD=myPassword psql -h 192.168.100.20 -d postgres -U postgres -p 5432 -a -q -c "Select * from test;"